### ISSUE TITLE
Why does the agreement accept endpoint require user_agent + ip_address

### ISSUE THREAD

**Issue by RobinTTY** [nordigen/nordigen-python#13]
Hi, this is more of a general question regarding the Nordigen API but I couldn't find any documentation describing why I need to provide a user agent and IP address in the request body when accepting an end user agreement via the API.

The route I am talking about: https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/agreements/accept%20EUA

Is this a case of "user A with IP X communicates with backend B with IP Y, which communicates with the API" and therefore the backend would need to communicate IP X (and user agent of user A) to the API?

Also do the values of these parameters have any implications on anything?

Edit: Another question: in what case is it possible to use this accept endpoint? (I'm getting: "Your company doesn't have permission to accept EUA")

**Comment by safriks** [comment]
Hi Robin,
Aleks from Nordigen Support here.

The PUT[​/api​/v2​/agreements​/enduser​/{id}​/accept​/](https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/agreements/accept%20EUA) endpiont is only available to larger customers after a serious background check and signing of an enterprise contract (EUR 5k+ a month) you can ask sales@nordigen.com for more details if you are interested.

But, otherwise accepting the EUA is just one click for the user.

**Comment by RobinTTY** [comment]
Thanks for the info!
